<a href="https://colab.research.google.com/github/SedyaPrograms/Tutorial/blob/main/AI%20and%20machine%20learning/ML_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [ ]:
x_data_np = np.array(data)

In [ ]:
x_data_np, x_data

(array([[1, 2],
        [3, 4]]), tensor([[1, 2],
         [3, 4]]))

In [ ]:
type(torch.ones((2, 5)).sum().item())

float

In [ ]:
torch.cuda.get_device_name()

'Tesla T4'

In [ ]:
device = 'cuda:0'
torch.ones((2, 5)).to(device)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], device='cuda:0')

Build model


In [ ]:
import torch
from torch import nn

class NeuralNetwork(nn.Module):
    def __init__(self, n_features, n_middle):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear = nn.Linear(n_features, n_middle)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.flatten(x)
        x = self.linear(x)
        result = self.relu(x)
        return result

In [ ]:
model = NeuralNetwork(28 * 28, 64).to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear): Linear(in_features=784, out_features=64, bias=True)
  (relu): ReLU()
)


In [ ]:
X = torch.rand(1, 28, 28, device=device)
result = model(X)

In [ ]:
result

tensor([[0.0000, 0.0000, 0.6775, 0.0543, 0.2320, 0.0000, 0.0000, 0.3692, 0.2418,
         0.2558, 0.2701, 0.0000, 0.0000, 0.1723, 0.0624, 0.9851, 0.0000, 0.0000,
         0.1889, 0.0000, 0.0000, 0.0000, 0.3652, 0.1141, 0.0000, 0.3003, 0.0000,
         0.5755, 0.3540, 0.4949, 0.0000, 0.5235, 0.2194, 0.3266, 0.0000, 0.0000,
         0.0429, 0.0000, 0.1373, 0.2028, 0.0000, 0.0959, 0.0328, 0.1669, 0.5447,
         0.2478, 0.0000, 0.0000, 0.0000, 0.5060, 0.3852, 0.0000, 0.7894, 0.0248,
         0.1341, 0.3328, 0.0000, 0.0931, 0.3147, 0.0048, 0.0000, 0.2793, 0.0000,
         0.2136]], device='cuda:0', grad_fn=<ReluBackward0>)

In [ ]:
seq_modules = nn.Sequential(
    nn.Flatten(),
    nn.Linear(28 * 28, 64),
    nn.ReLU(),
)

In [ ]:
X = torch.rand(1, 28, 28, device='cpu')
result = seq_modules(X)

In [ ]:
for name, param in seq_modules.named_parameters():
    print(f"Layer: {name} | Size: {param.size()} | Values : {param[:2]} \n")

Layer: 1.weight | Size: torch.Size([64, 784]) | Values : tensor([[-0.0318, -0.0215,  0.0044,  ...,  0.0138, -0.0219,  0.0225],
        [ 0.0027,  0.0314, -0.0222,  ..., -0.0075, -0.0305,  0.0177]],
       grad_fn=<SliceBackward0>) 

Layer: 1.bias | Size: torch.Size([64]) | Values : tensor([0.0079, 0.0117], grad_fn=<SliceBackward0>) 



In [ ]:
result.shape

torch.Size([1, 64])